/*
 * Inferno guest-to-host Metal execution bridge.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef STANDARD_HEADERS_INFERNO_METAL_H
#define STANDARD_HEADERS_INFERNO_METAL_H

#include <stdint.h>

#define INFERNO_METAL_MAGIC 0x4c544d49U
#define INFERNO_METAL_VERSION 2U
#define INFERNO_METAL_DESCRIPTOR_SIZE 256U
#define INFERNO_METAL_MAX_SOURCE (64U * 1024U)
#define INFERNO_METAL_MAX_BUFFER (16U * 1024U * 1024U)
#define INFERNO_METAL_MAX_THREADS (16U * 1024U * 1024U)

enum {
    INFERNO_METAL_COMPUTE = 1,
    INFERNO_METAL_RENDER = 2,
    INFERNO_METAL_CLEAR = 3,
    INFERNO_METAL_QUERY_LIBRARY = 4,
    INFERNO_METAL_QUERY_PIPELINE = 5,
};

enum {
    INFERNO_METAL_OPTIONS_DEFAULT = 0,
};

enum {
    INFERNO_METAL_DESCRIPTOR_OPTIONS_OFFSET = 192,
    INFERNO_METAL_DESCRIPTOR_RESERVED_OFFSET = 196,
    INFERNO_METAL_DESCRIPTOR_RESERVED_SIZE = 60,
};

#define INFERNO_METAL_COMPILER_HEADER_SIZE 64U
#define INFERNO_METAL_COMPILER_DOMAIN_SIZE 128U
#define INFERNO_METAL_COMPILER_DESCRIPTION_SIZE 16384U
#define INFERNO_METAL_COMPILER_FUNCTION_RECORD_SIZE 256U
#define INFERNO_METAL_COMPILER_FUNCTION_NAME_SIZE 248U
#define INFERNO_METAL_COMPILER_MAX_FUNCTIONS 1024U
#define INFERNO_METAL_COMPILER_MIN_OUTPUT 16592U
#define INFERNO_METAL_COMPILER_MAX_OUTPUT   \
    (INFERNO_METAL_COMPILER_MIN_OUTPUT +    \
     INFERNO_METAL_COMPILER_MAX_FUNCTIONS * \
         INFERNO_METAL_COMPILER_FUNCTION_RECORD_SIZE)

enum {
    INFERNO_METAL_COMPILER_VERSION_OFFSET = 0,
    INFERNO_METAL_COMPILER_OPCODE_OFFSET = 4,
    INFERNO_METAL_COMPILER_SEQUENCE_OFFSET = 8,
    INFERNO_METAL_COMPILER_OUTCOME_OFFSET = 16,
    INFERNO_METAL_COMPILER_PHASE_OFFSET = 20,
    INFERNO_METAL_COMPILER_FLAGS_OFFSET = 24,
    INFERNO_METAL_COMPILER_FUNCTION_COUNT_OFFSET = 28,
    INFERNO_METAL_COMPILER_FUNCTION_TYPE_OFFSET = 32,
    INFERNO_METAL_COMPILER_MAX_TOTAL_THREADS_OFFSET = 36,
    INFERNO_METAL_COMPILER_THREAD_EXECUTION_WIDTH_OFFSET = 40,
    INFERNO_METAL_COMPILER_STATIC_THREADGROUP_MEMORY_OFFSET = 44,
    INFERNO_METAL_COMPILER_RESERVED_OFFSET = 48,
    INFERNO_METAL_COMPILER_RESERVED_SIZE = 16,
    INFERNO_METAL_COMPILER_ERROR_CODE_OFFSET = 64,
    INFERNO_METAL_COMPILER_DOMAIN_LENGTH_OFFSET = 72,
    INFERNO_METAL_COMPILER_DESCRIPTION_LENGTH_OFFSET = 76,
    INFERNO_METAL_COMPILER_DOMAIN_OFFSET = 80,
    INFERNO_METAL_COMPILER_DESCRIPTION_OFFSET = 208,
    INFERNO_METAL_COMPILER_FUNCTIONS_OFFSET = 16592,
};

enum {
    INFERNO_METAL_COMPILER_RECORD_TYPE_OFFSET = 0,
    INFERNO_METAL_COMPILER_RECORD_NAME_LENGTH_OFFSET = 4,
    INFERNO_METAL_COMPILER_RECORD_NAME_OFFSET = 8,
};

enum {
    INFERNO_METAL_COMPILER_OUTCOME_OK = 0,
    INFERNO_METAL_COMPILER_OUTCOME_COMPILE_FAILED = 1,
    INFERNO_METAL_COMPILER_OUTCOME_FUNCTION_NOT_FOUND = 2,
    INFERNO_METAL_COMPILER_OUTCOME_FUNCTION_TYPE_MISMATCH = 3,
    INFERNO_METAL_COMPILER_OUTCOME_INVENTORY_UNSUPPORTED = 4,
    INFERNO_METAL_COMPILER_OUTCOME_OUTPUT_TOO_SMALL = 5,
};

enum {
    INFERNO_METAL_COMPILER_PHASE_NONE = 0,
    INFERNO_METAL_COMPILER_PHASE_LIBRARY = 1,
    INFERNO_METAL_COMPILER_PHASE_INVENTORY = 2,
    INFERNO_METAL_COMPILER_PHASE_FUNCTION = 3,
    INFERNO_METAL_COMPILER_PHASE_PIPELINE = 4,
};

enum {
    INFERNO_METAL_COMPILER_FLAG_DESCRIPTION_TRUNCATED = 1U << 0,
    INFERNO_METAL_COMPILER_FLAG_DOMAIN_TRUNCATED = 1U << 1,
    INFERNO_METAL_COMPILER_FLAG_NO_NSERROR = 1U << 2,
    INFERNO_METAL_COMPILER_FLAG_WARNING = 1U << 3,
    INFERNO_METAL_COMPILER_FLAG_MASK =
        INFERNO_METAL_COMPILER_FLAG_DESCRIPTION_TRUNCATED |
        INFERNO_METAL_COMPILER_FLAG_DOMAIN_TRUNCATED |
        INFERNO_METAL_COMPILER_FLAG_NO_NSERROR |
        INFERNO_METAL_COMPILER_FLAG_WARNING,
};

enum {
    INFERNO_METAL_FUNCTION_TYPE_VERTEX = 1,
    INFERNO_METAL_FUNCTION_TYPE_FRAGMENT = 2,
    INFERNO_METAL_FUNCTION_TYPE_KERNEL = 3,
    INFERNO_METAL_FUNCTION_TYPE_VISIBLE = 5,
    INFERNO_METAL_FUNCTION_TYPE_INTERSECTION = 6,
    INFERNO_METAL_FUNCTION_TYPE_MESH = 7,
    INFERNO_METAL_FUNCTION_TYPE_OBJECT = 8,
};

enum {
    INFERNO_METAL_IDLE = 0,
    INFERNO_METAL_BUSY = 1,
    INFERNO_METAL_DONE = 2,
    INFERNO_METAL_FAILED = 3,
};

enum {
    INFERNO_METAL_OK = 0,
    INFERNO_METAL_BAD_DESCRIPTOR = 1,
    INFERNO_METAL_BAD_MEMORY = 2,
    INFERNO_METAL_BACKEND_ERROR = 3,
};

/* Native field representation; serialize explicitly as little endian. */
typedef struct InfernoMetalCommand {
    uint32_t opcode;
    uint64_t sequence;
    uint64_t source_gpa;
    uint32_t source_size;
    uint32_t input_size;
    uint64_t input_gpa;
    uint64_t output_gpa;
    uint32_t output_size;
    uint32_t width;
    uint32_t height;
    /* Compute depth, or render vertex count. */
    uint32_t depth;
    uint32_t options;
    char function[64];
    char fragment[64];
} InfernoMetalCommand;

/* Byte offsets of aligned 32-bit little-endian device registers. */
enum {
    INFERNO_METAL_REG_MAGIC = 0x00,
    INFERNO_METAL_REG_VERSION = 0x04,
    INFERNO_METAL_REG_STATUS = 0x08,
    INFERNO_METAL_REG_ERROR = 0x0c,
    INFERNO_METAL_REG_DESCRIPTOR_LO = 0x10,
    INFERNO_METAL_REG_DESCRIPTOR_HI = 0x14,
    INFERNO_METAL_REG_SUBMIT = 0x18,
    INFERNO_METAL_REG_SEQUENCE_LO = 0x20,
    INFERNO_METAL_REG_SEQUENCE_HI = 0x24,
    INFERNO_METAL_REG_PENDING = 0x28,
    INFERNO_METAL_REG_IRQ_ENABLE = 0x2c,
    INFERNO_METAL_REG_ACK = 0x30,
    INFERNO_METAL_REG_RESET = 0x34,
    INFERNO_METAL_REGISTER_SIZE = 0x38,
};

#endif
