/*
 * Inferno guest-to-host Metal execution bridge.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef STANDARD_HEADERS_INFERNO_METAL_H
#define STANDARD_HEADERS_INFERNO_METAL_H

#include <stdint.h>

#define INFERNO_METAL_MAGIC 0x4c544d49U
#define INFERNO_METAL_VERSION 5U
#define INFERNO_METAL_DESCRIPTOR_SIZE 256U
#define INFERNO_METAL_MAX_SOURCE (64U * 1024U)
#define INFERNO_METAL_MAX_BUFFER (16U * 1024U * 1024U)
#define INFERNO_METAL_MAX_THREADS (16U * 1024U * 1024U)

enum {
    INFERNO_METAL_COMPUTE = 1,
    INFERNO_METAL_RENDER = 2,
    INFERNO_METAL_CLEAR = 3,
    INFERNO_METAL_QUERY_LIBRARY = 4,
    INFERNO_METAL_QUERY_PIPELINE = 5,
    INFERNO_METAL_QUERY_IMAGEBLOCK = 6,
    INFERNO_METAL_BATCH = 7,
    INFERNO_METAL_BATCH_RESOURCES = 8,
    INFERNO_METAL_QUERY_LIBRARY_TYPED = 9,
    INFERNO_METAL_QUERY_PIPELINE_TYPED = 10,
    INFERNO_METAL_QUERY_RENDER_PIPELINE = 11,
    INFERNO_METAL_QUERY_IMAGEBLOCK_TYPED = 12,
};

#define INFERNO_METAL_BATCH_HEADER_SIZE 64U
#define INFERNO_METAL_BATCH_PIPELINE_RECORD_SIZE 80U
#define INFERNO_METAL_BATCH_BUFFER_RECORD_SIZE 16U
#define INFERNO_METAL_BATCH_DISPATCH_RECORD_SIZE 64U
#define INFERNO_METAL_BATCH_BINDING_RECORD_SIZE 32U
#define INFERNO_METAL_BATCH_RESULT_SIZE 16640U
#define INFERNO_METAL_BATCH_MAX_PIPELINES 8U
#define INFERNO_METAL_BATCH_MAX_BUFFERS 64U
#define INFERNO_METAL_BATCH_MAX_DISPATCHES 64U
#define INFERNO_METAL_BATCH_MAX_BINDINGS 1024U
#define INFERNO_METAL_BATCH_MAX_INLINE (64U * 1024U)
#define INFERNO_METAL_BATCH_MAX_SOURCE \
    (INFERNO_METAL_BATCH_MAX_PIPELINES * INFERNO_METAL_MAX_SOURCE)
#define INFERNO_METAL_BATCH_MAX_BUFFER_LENGTH \
    (INFERNO_METAL_MAX_BUFFER - INFERNO_METAL_BATCH_MAX_INLINE)
#define INFERNO_METAL_BATCH_MAX_IMAGES \
    (INFERNO_METAL_MAX_BUFFER - INFERNO_METAL_BATCH_RESULT_SIZE)

enum {
    INFERNO_METAL_BATCH_VERSION_OFFSET = 0,
    INFERNO_METAL_BATCH_FLAGS_OFFSET = 4,
    INFERNO_METAL_BATCH_PIPELINE_COUNT_OFFSET = 8,
    INFERNO_METAL_BATCH_BUFFER_COUNT_OFFSET = 12,
    INFERNO_METAL_BATCH_DISPATCH_COUNT_OFFSET = 16,
    INFERNO_METAL_BATCH_BINDING_COUNT_OFFSET = 20,
    INFERNO_METAL_BATCH_INLINE_SIZE_OFFSET = 24,
    INFERNO_METAL_BATCH_SOURCE_SIZE_OFFSET = 28,
    INFERNO_METAL_BATCH_IMAGES_SIZE_OFFSET = 32,
    INFERNO_METAL_BATCH_RESERVED_OFFSET = 36,
    INFERNO_METAL_BATCH_RESERVED_SIZE = 28,
};

enum {
    INFERNO_METAL_BATCH_PIPELINE_SOURCE_OFFSET = 0,
    INFERNO_METAL_BATCH_PIPELINE_SOURCE_SIZE_OFFSET = 4,
    INFERNO_METAL_BATCH_PIPELINE_FLAGS_OFFSET = 8,
    INFERNO_METAL_BATCH_PIPELINE_RESERVED_OFFSET = 12,
    INFERNO_METAL_BATCH_PIPELINE_NAME_OFFSET = 16,
};

enum {
    INFERNO_METAL_BATCH_BUFFER_LENGTH_OFFSET = 0,
    INFERNO_METAL_BATCH_BUFFER_FLAGS_OFFSET = 4,
    INFERNO_METAL_BATCH_BUFFER_RESERVED_OFFSET = 8,
};

enum {
    INFERNO_METAL_BATCH_DISPATCH_PIPELINE_OFFSET = 0,
    INFERNO_METAL_BATCH_DISPATCH_MODE_OFFSET = 4,
    INFERNO_METAL_BATCH_DISPATCH_BINDING_START_OFFSET = 8,
    INFERNO_METAL_BATCH_DISPATCH_BINDING_COUNT_OFFSET = 12,
    INFERNO_METAL_BATCH_DISPATCH_GRID_WIDTH_OFFSET = 16,
    INFERNO_METAL_BATCH_DISPATCH_GRID_HEIGHT_OFFSET = 20,
    INFERNO_METAL_BATCH_DISPATCH_GRID_DEPTH_OFFSET = 24,
    INFERNO_METAL_BATCH_DISPATCH_GROUP_WIDTH_OFFSET = 28,
    INFERNO_METAL_BATCH_DISPATCH_GROUP_HEIGHT_OFFSET = 32,
    INFERNO_METAL_BATCH_DISPATCH_GROUP_DEPTH_OFFSET = 36,
    INFERNO_METAL_BATCH_DISPATCH_FLAGS_OFFSET = 40,
    INFERNO_METAL_BATCH_DISPATCH_RESERVED_OFFSET = 44,
    INFERNO_METAL_BATCH_DISPATCH_RESERVED_SIZE = 20,
};

enum {
    INFERNO_METAL_BATCH_BINDING_KIND_OFFSET = 0,
    INFERNO_METAL_BATCH_BINDING_INDEX_OFFSET = 4,
    INFERNO_METAL_BATCH_BINDING_RESOURCE_OFFSET = 8,
    INFERNO_METAL_BATCH_BINDING_LENGTH_OFFSET = 12,
    INFERNO_METAL_BATCH_BINDING_OFFSET_OFFSET = 16,
    INFERNO_METAL_BATCH_BINDING_RESERVED_OFFSET = 24,
};

enum {
    INFERNO_METAL_BATCH_DISPATCH_THREADS = 1,
    INFERNO_METAL_BATCH_DISPATCH_THREADGROUPS = 2,
};

enum {
    INFERNO_METAL_BATCH_BINDING_BUFFER = 1,
    INFERNO_METAL_BATCH_BINDING_INLINE = 2,
    INFERNO_METAL_BATCH_BINDING_THREADGROUP = 3,
};

enum {
    INFERNO_METAL_BATCH_RESULT_VERSION_OFFSET = 0,
    INFERNO_METAL_BATCH_RESULT_OPCODE_OFFSET = 4,
    INFERNO_METAL_BATCH_RESULT_SEQUENCE_OFFSET = 8,
    INFERNO_METAL_BATCH_RESULT_OUTCOME_OFFSET = 16,
    INFERNO_METAL_BATCH_RESULT_PHASE_OFFSET = 20,
    INFERNO_METAL_BATCH_RESULT_FLAGS_OFFSET = 24,
    INFERNO_METAL_BATCH_RESULT_FAILED_KIND_OFFSET = 28,
    INFERNO_METAL_BATCH_RESULT_FAILED_INDEX_OFFSET = 32,
    INFERNO_METAL_BATCH_RESULT_BUFFER_COUNT_OFFSET = 36,
    INFERNO_METAL_BATCH_RESULT_IMAGES_SIZE_OFFSET = 40,
    INFERNO_METAL_BATCH_RESULT_HOST_STATUS_OFFSET = 44,
    INFERNO_METAL_BATCH_RESULT_RESERVED0_OFFSET = 48,
    INFERNO_METAL_BATCH_RESULT_RESERVED0_SIZE = 16,
    INFERNO_METAL_BATCH_RESULT_ERROR_CODE_OFFSET = 64,
    INFERNO_METAL_BATCH_RESULT_DOMAIN_LENGTH_OFFSET = 72,
    INFERNO_METAL_BATCH_RESULT_DESCRIPTION_LENGTH_OFFSET = 76,
    INFERNO_METAL_BATCH_RESULT_DOMAIN_OFFSET = 80,
    INFERNO_METAL_BATCH_RESULT_DESCRIPTION_OFFSET = 208,
    INFERNO_METAL_BATCH_RESULT_RESERVED1_OFFSET = 16592,
    INFERNO_METAL_BATCH_RESULT_RESERVED1_SIZE = 48,
    INFERNO_METAL_BATCH_RESULT_IMAGES_OFFSET = 16640,
};

enum {
    INFERNO_METAL_BATCH_OUTCOME_OK = 0,
    INFERNO_METAL_BATCH_OUTCOME_MALFORMED = 1,
    INFERNO_METAL_BATCH_OUTCOME_COMPILE_FAILED = 2,
    INFERNO_METAL_BATCH_OUTCOME_FUNCTION_NOT_FOUND = 3,
    INFERNO_METAL_BATCH_OUTCOME_FUNCTION_TYPE_MISMATCH = 4,
    INFERNO_METAL_BATCH_OUTCOME_SPECIALIZATION_REQUIRED = 5,
    INFERNO_METAL_BATCH_OUTCOME_INVALID_DISPATCH = 6,
    INFERNO_METAL_BATCH_OUTCOME_EXECUTION_FAILED = 7,
    INFERNO_METAL_BATCH_OUTCOME_UNSUPPORTED_HOST = 8,
};

enum {
    INFERNO_METAL_BATCH_PHASE_NONE = 0,
    INFERNO_METAL_BATCH_PHASE_PARSE = 1,
    INFERNO_METAL_BATCH_PHASE_LIBRARY = 2,
    INFERNO_METAL_BATCH_PHASE_FUNCTION = 3,
    INFERNO_METAL_BATCH_PHASE_PIPELINE = 4,
    INFERNO_METAL_BATCH_PHASE_VALIDATE = 5,
    INFERNO_METAL_BATCH_PHASE_EXECUTE = 6,
};

enum {
    INFERNO_METAL_BATCH_RECORD_UNKNOWN = 0,
    INFERNO_METAL_BATCH_RECORD_HEADER = 1,
    INFERNO_METAL_BATCH_RECORD_PIPELINE = 2,
    INFERNO_METAL_BATCH_RECORD_BUFFER = 3,
    INFERNO_METAL_BATCH_RECORD_DISPATCH = 4,
    INFERNO_METAL_BATCH_RECORD_BINDING = 5,
};

enum {
    INFERNO_METAL_BATCH_FLAG_DESCRIPTION_TRUNCATED = 1U << 0,
    INFERNO_METAL_BATCH_FLAG_DOMAIN_TRUNCATED = 1U << 1,
    INFERNO_METAL_BATCH_FLAG_NO_NSERROR = 1U << 2,
    INFERNO_METAL_BATCH_FLAG_WARNING = 1U << 3,
    INFERNO_METAL_BATCH_FLAG_SCHEDULED = 1U << 4,
    INFERNO_METAL_BATCH_FLAG_MASK =
        INFERNO_METAL_BATCH_FLAG_DESCRIPTION_TRUNCATED |
        INFERNO_METAL_BATCH_FLAG_DOMAIN_TRUNCATED |
        INFERNO_METAL_BATCH_FLAG_NO_NSERROR | INFERNO_METAL_BATCH_FLAG_WARNING |
        INFERNO_METAL_BATCH_FLAG_SCHEDULED,
};

enum {
    INFERNO_METAL_HOST_COMMAND_BUFFER_COMPLETED = 4,
    INFERNO_METAL_HOST_COMMAND_BUFFER_ERROR = 5,
};

#define INFERNO_METAL_BATCH_FAILED_INDEX_UNKNOWN UINT32_MAX

/* Version-5 resource manifests and typed compiler queries. */
#define INFERNO_METAL_RESOURCE_VERSION 5U
#define INFERNO_METAL_RESOURCE_HEADER_SIZE 128U
#define INFERNO_METAL_RESOURCE_LIBRARY_RECORD_SIZE 32U
#define INFERNO_METAL_RESOURCE_COMPUTE_PIPELINE_RECORD_SIZE 80U
#define INFERNO_METAL_RESOURCE_RENDER_PIPELINE_RECORD_SIZE 192U
#define INFERNO_METAL_RESOURCE_BUFFER_RECORD_SIZE 16U
#define INFERNO_METAL_RESOURCE_TEXTURE_RECORD_SIZE 32U
#define INFERNO_METAL_RESOURCE_SAMPLER_RECORD_SIZE 80U
#define INFERNO_METAL_RESOURCE_COMMAND_RECORD_SIZE 96U
#define INFERNO_METAL_RESOURCE_DRAW_RECORD_SIZE 160U
#define INFERNO_METAL_RESOURCE_BINDING_RECORD_SIZE 32U
#define INFERNO_METAL_RESOURCE_RESULT_SIZE 16640U
#define INFERNO_METAL_RESOURCE_QUERY_HEADER_SIZE 64U
#define INFERNO_METAL_RESOURCE_RENDER_RESULT_SIZE 512U
#define INFERNO_METAL_RESOURCE_COMPILER_RENDER_RESULT_OFFSET 16656U
#define INFERNO_METAL_RESOURCE_MAX_LIBRARIES 16U
#define INFERNO_METAL_RESOURCE_MAX_COMPUTE_PIPELINES 8U
#define INFERNO_METAL_RESOURCE_MAX_RENDER_PIPELINES 8U
#define INFERNO_METAL_RESOURCE_MAX_BUFFERS 64U
#define INFERNO_METAL_RESOURCE_MAX_TEXTURES 32U
#define INFERNO_METAL_RESOURCE_MAX_SAMPLERS 32U
#define INFERNO_METAL_RESOURCE_MAX_COMMANDS 64U
#define INFERNO_METAL_RESOURCE_MAX_DRAWS 256U
#define INFERNO_METAL_RESOURCE_MAX_BINDINGS 2048U
#define INFERNO_METAL_RESOURCE_MAX_INLINE (64U * 1024U)
#define INFERNO_METAL_RESOURCE_MAX_INLINE_BINDING 4096U
#define INFERNO_METAL_RESOURCE_MAX_THREADGROUP_MEMORY 32768U
#define INFERNO_METAL_RESOURCE_MAX_PAYLOAD (8U * 1024U * 1024U)
#define INFERNO_METAL_RESOURCE_MAX_METALLIB (4U * 1024U * 1024U)
#define INFERNO_METAL_RESOURCE_MAX_TEXTURE_DIMENSION 8192U
#define INFERNO_METAL_RESOURCE_TEXTURE_BYTES_PER_PIXEL 4U
#define INFERNO_METAL_RESOURCE_MAX_IMAGES \
    (INFERNO_METAL_MAX_BUFFER - INFERNO_METAL_RESOURCE_RESULT_SIZE)

enum {
    INFERNO_METAL_RESOURCE_VERSION_OFFSET = 0,
    INFERNO_METAL_RESOURCE_FLAGS_OFFSET = 4,
    INFERNO_METAL_RESOURCE_LIBRARY_COUNT_OFFSET = 8,
    INFERNO_METAL_RESOURCE_COMPUTE_PIPELINE_COUNT_OFFSET = 12,
    INFERNO_METAL_RESOURCE_RENDER_PIPELINE_COUNT_OFFSET = 16,
    INFERNO_METAL_RESOURCE_BUFFER_COUNT_OFFSET = 20,
    INFERNO_METAL_RESOURCE_TEXTURE_COUNT_OFFSET = 24,
    INFERNO_METAL_RESOURCE_SAMPLER_COUNT_OFFSET = 28,
    INFERNO_METAL_RESOURCE_HEADER_COMMAND_COUNT_OFFSET = 32,
    INFERNO_METAL_RESOURCE_DRAW_COUNT_OFFSET = 36,
    INFERNO_METAL_RESOURCE_BINDING_COUNT_OFFSET = 40,
    INFERNO_METAL_RESOURCE_INLINE_SIZE_OFFSET = 44,
    INFERNO_METAL_RESOURCE_PAYLOAD_SIZE_OFFSET = 48,
    INFERNO_METAL_RESOURCE_IMAGES_SIZE_OFFSET = 52,
    INFERNO_METAL_RESOURCE_RESERVED_OFFSET = 56,
    INFERNO_METAL_RESOURCE_RESERVED_SIZE = 72,
};

enum {
    INFERNO_METAL_RESOURCE_LIBRARY_KIND_OFFSET = 0,
    INFERNO_METAL_RESOURCE_LIBRARY_PAYLOAD_OFFSET = 4,
    INFERNO_METAL_RESOURCE_LIBRARY_PAYLOAD_SIZE_OFFSET = 8,
    INFERNO_METAL_RESOURCE_LIBRARY_FLAGS_OFFSET = 12,
    INFERNO_METAL_RESOURCE_LIBRARY_RESERVED_OFFSET = 16,
    INFERNO_METAL_RESOURCE_LIBRARY_RESERVED_SIZE = 16,
};

enum {
    INFERNO_METAL_RESOURCE_COMPUTE_PIPELINE_LIBRARY_OFFSET = 0,
    INFERNO_METAL_RESOURCE_COMPUTE_PIPELINE_FLAGS_OFFSET = 4,
    INFERNO_METAL_RESOURCE_COMPUTE_PIPELINE_RESERVED_OFFSET = 8,
    INFERNO_METAL_RESOURCE_COMPUTE_PIPELINE_RESERVED_SIZE = 8,
    INFERNO_METAL_RESOURCE_COMPUTE_PIPELINE_NAME_OFFSET = 16,
    INFERNO_METAL_RESOURCE_FUNCTION_NAME_SIZE = 64,
};

enum {
    INFERNO_METAL_RESOURCE_RENDER_PIPELINE_VERTEX_LIBRARY_OFFSET = 0,
    INFERNO_METAL_RESOURCE_RENDER_PIPELINE_FRAGMENT_LIBRARY_OFFSET = 4,
    INFERNO_METAL_RESOURCE_RENDER_PIPELINE_PIXEL_FORMAT_OFFSET = 8,
    INFERNO_METAL_RESOURCE_RENDER_PIPELINE_SAMPLE_COUNT_OFFSET = 12,
    INFERNO_METAL_RESOURCE_RENDER_PIPELINE_BLENDING_ENABLED_OFFSET = 16,
    INFERNO_METAL_RESOURCE_RENDER_PIPELINE_SOURCE_RGB_FACTOR_OFFSET = 20,
    INFERNO_METAL_RESOURCE_RENDER_PIPELINE_DESTINATION_RGB_FACTOR_OFFSET = 24,
    INFERNO_METAL_RESOURCE_RENDER_PIPELINE_RGB_OPERATION_OFFSET = 28,
    INFERNO_METAL_RESOURCE_RENDER_PIPELINE_SOURCE_ALPHA_FACTOR_OFFSET = 32,
    INFERNO_METAL_RESOURCE_RENDER_PIPELINE_DESTINATION_ALPHA_FACTOR_OFFSET = 36,
    INFERNO_METAL_RESOURCE_RENDER_PIPELINE_ALPHA_OPERATION_OFFSET = 40,
    INFERNO_METAL_RESOURCE_RENDER_PIPELINE_WRITE_MASK_OFFSET = 44,
    INFERNO_METAL_RESOURCE_RENDER_PIPELINE_FLAGS_OFFSET = 48,
    INFERNO_METAL_RESOURCE_RENDER_PIPELINE_RESERVED_OFFSET = 52,
    INFERNO_METAL_RESOURCE_RENDER_PIPELINE_RESERVED_SIZE = 12,
    INFERNO_METAL_RESOURCE_RENDER_PIPELINE_VERTEX_NAME_OFFSET = 64,
    INFERNO_METAL_RESOURCE_RENDER_PIPELINE_FRAGMENT_NAME_OFFSET = 128,
};

enum {
    INFERNO_METAL_RESOURCE_BUFFER_LENGTH_OFFSET = 0,
    INFERNO_METAL_RESOURCE_BUFFER_FLAGS_OFFSET = 4,
    INFERNO_METAL_RESOURCE_BUFFER_RESERVED_OFFSET = 8,
    INFERNO_METAL_RESOURCE_BUFFER_RESERVED_SIZE = 8,
};

enum {
    INFERNO_METAL_RESOURCE_TEXTURE_WIDTH_OFFSET = 0,
    INFERNO_METAL_RESOURCE_TEXTURE_HEIGHT_OFFSET = 4,
    INFERNO_METAL_RESOURCE_TEXTURE_PIXEL_FORMAT_OFFSET = 8,
    INFERNO_METAL_RESOURCE_TEXTURE_USAGE_OFFSET = 12,
    INFERNO_METAL_RESOURCE_TEXTURE_FLAGS_OFFSET = 16,
    INFERNO_METAL_RESOURCE_TEXTURE_RESERVED_OFFSET = 20,
    INFERNO_METAL_RESOURCE_TEXTURE_RESERVED_SIZE = 12,
};

enum {
    INFERNO_METAL_RESOURCE_SAMPLER_MIN_FILTER_OFFSET = 0,
    INFERNO_METAL_RESOURCE_SAMPLER_MAG_FILTER_OFFSET = 4,
    INFERNO_METAL_RESOURCE_SAMPLER_MIP_FILTER_OFFSET = 8,
    INFERNO_METAL_RESOURCE_SAMPLER_MAX_ANISOTROPY_OFFSET = 12,
    INFERNO_METAL_RESOURCE_SAMPLER_S_ADDRESS_MODE_OFFSET = 16,
    INFERNO_METAL_RESOURCE_SAMPLER_T_ADDRESS_MODE_OFFSET = 20,
    INFERNO_METAL_RESOURCE_SAMPLER_R_ADDRESS_MODE_OFFSET = 24,
    INFERNO_METAL_RESOURCE_SAMPLER_BORDER_COLOR_OFFSET = 28,
    INFERNO_METAL_RESOURCE_SAMPLER_REDUCTION_MODE_OFFSET = 32,
    INFERNO_METAL_RESOURCE_SAMPLER_NORMALIZED_COORDINATES_OFFSET = 36,
    INFERNO_METAL_RESOURCE_SAMPLER_LOD_MIN_CLAMP_OFFSET = 40,
    INFERNO_METAL_RESOURCE_SAMPLER_LOD_MAX_CLAMP_OFFSET = 44,
    INFERNO_METAL_RESOURCE_SAMPLER_LOD_AVERAGE_OFFSET = 48,
    INFERNO_METAL_RESOURCE_SAMPLER_LOD_BIAS_OFFSET = 52,
    INFERNO_METAL_RESOURCE_SAMPLER_COMPARE_FUNCTION_OFFSET = 56,
    INFERNO_METAL_RESOURCE_SAMPLER_SUPPORT_ARGUMENT_BUFFERS_OFFSET = 60,
    INFERNO_METAL_RESOURCE_SAMPLER_FLAGS_OFFSET = 64,
    INFERNO_METAL_RESOURCE_SAMPLER_RESERVED_OFFSET = 68,
    INFERNO_METAL_RESOURCE_SAMPLER_RESERVED_SIZE = 12,
};

enum {
    INFERNO_METAL_RESOURCE_COMMAND_KIND_OFFSET = 0,
    INFERNO_METAL_RESOURCE_COMMAND_FLAGS_OFFSET = 4,
    INFERNO_METAL_RESOURCE_COMMAND_RESOURCE_OFFSET = 8,
    INFERNO_METAL_RESOURCE_COMMAND_ACTION_OFFSET = 12,
    INFERNO_METAL_RESOURCE_COMMAND_COUNT_OR_ACTION_OFFSET = 16,
    INFERNO_METAL_RESOURCE_COMMAND_START_OFFSET = 20,
    INFERNO_METAL_RESOURCE_COMMAND_COUNT_OFFSET = 24,
    INFERNO_METAL_RESOURCE_COMMAND_COMPUTE_GRID_HEIGHT_OFFSET = 28,
    INFERNO_METAL_RESOURCE_COMMAND_COMPUTE_GRID_DEPTH_OFFSET = 32,
    INFERNO_METAL_RESOURCE_COMMAND_COMPUTE_GROUP_WIDTH_OFFSET = 36,
    INFERNO_METAL_RESOURCE_COMMAND_COMPUTE_GROUP_HEIGHT_OFFSET = 40,
    INFERNO_METAL_RESOURCE_COMMAND_COMPUTE_GROUP_DEPTH_OFFSET = 44,
    INFERNO_METAL_RESOURCE_COMMAND_COMPUTE_RESERVED_OFFSET = 48,
    INFERNO_METAL_RESOURCE_COMMAND_COMPUTE_RESERVED_SIZE = 48,
    INFERNO_METAL_RESOURCE_COMMAND_RENDER_UNUSED_OFFSET = 28,
    INFERNO_METAL_RESOURCE_COMMAND_RENDER_CLEAR_RED_OFFSET = 32,
    INFERNO_METAL_RESOURCE_COMMAND_RENDER_CLEAR_GREEN_OFFSET = 40,
    INFERNO_METAL_RESOURCE_COMMAND_RENDER_CLEAR_BLUE_OFFSET = 48,
    INFERNO_METAL_RESOURCE_COMMAND_RENDER_CLEAR_ALPHA_OFFSET = 56,
    INFERNO_METAL_RESOURCE_COMMAND_RENDER_RESERVED_OFFSET = 64,
    INFERNO_METAL_RESOURCE_COMMAND_RENDER_RESERVED_SIZE = 32,
};

enum {
    INFERNO_METAL_RESOURCE_COMMAND_COMPUTE_PIPELINE_OFFSET =
        INFERNO_METAL_RESOURCE_COMMAND_RESOURCE_OFFSET,
    INFERNO_METAL_RESOURCE_COMMAND_COMPUTE_MODE_OFFSET =
        INFERNO_METAL_RESOURCE_COMMAND_ACTION_OFFSET,
    INFERNO_METAL_RESOURCE_COMMAND_COMPUTE_BINDING_START_OFFSET =
        INFERNO_METAL_RESOURCE_COMMAND_COUNT_OR_ACTION_OFFSET,
    INFERNO_METAL_RESOURCE_COMMAND_COMPUTE_BINDING_COUNT_OFFSET =
        INFERNO_METAL_RESOURCE_COMMAND_START_OFFSET,
    INFERNO_METAL_RESOURCE_COMMAND_COMPUTE_GRID_WIDTH_OFFSET =
        INFERNO_METAL_RESOURCE_COMMAND_COUNT_OFFSET,
    INFERNO_METAL_RESOURCE_COMMAND_RENDER_TEXTURE_OFFSET =
        INFERNO_METAL_RESOURCE_COMMAND_RESOURCE_OFFSET,
    INFERNO_METAL_RESOURCE_COMMAND_RENDER_LOAD_ACTION_OFFSET =
        INFERNO_METAL_RESOURCE_COMMAND_ACTION_OFFSET,
    INFERNO_METAL_RESOURCE_COMMAND_RENDER_STORE_ACTION_OFFSET =
        INFERNO_METAL_RESOURCE_COMMAND_COUNT_OR_ACTION_OFFSET,
    INFERNO_METAL_RESOURCE_COMMAND_RENDER_DRAW_START_OFFSET =
        INFERNO_METAL_RESOURCE_COMMAND_START_OFFSET,
    INFERNO_METAL_RESOURCE_COMMAND_RENDER_DRAW_COUNT_OFFSET =
        INFERNO_METAL_RESOURCE_COMMAND_COUNT_OFFSET,
};

enum {
    INFERNO_METAL_RESOURCE_DRAW_PIPELINE_OFFSET = 0,
    INFERNO_METAL_RESOURCE_DRAW_PRIMITIVE_TYPE_OFFSET = 4,
    INFERNO_METAL_RESOURCE_DRAW_VERTEX_START_OFFSET = 8,
    INFERNO_METAL_RESOURCE_DRAW_VERTEX_COUNT_OFFSET = 12,
    INFERNO_METAL_RESOURCE_DRAW_INSTANCE_COUNT_OFFSET = 16,
    INFERNO_METAL_RESOURCE_DRAW_BASE_INSTANCE_OFFSET = 20,
    INFERNO_METAL_RESOURCE_DRAW_VERTEX_BINDING_START_OFFSET = 24,
    INFERNO_METAL_RESOURCE_DRAW_VERTEX_BINDING_COUNT_OFFSET = 28,
    INFERNO_METAL_RESOURCE_DRAW_FRAGMENT_BINDING_START_OFFSET = 32,
    INFERNO_METAL_RESOURCE_DRAW_FRAGMENT_BINDING_COUNT_OFFSET = 36,
    INFERNO_METAL_RESOURCE_DRAW_CULL_MODE_OFFSET = 40,
    INFERNO_METAL_RESOURCE_DRAW_WINDING_OFFSET = 44,
    INFERNO_METAL_RESOURCE_DRAW_FILL_MODE_OFFSET = 48,
    INFERNO_METAL_RESOURCE_DRAW_FLAGS_OFFSET = 52,
    INFERNO_METAL_RESOURCE_DRAW_SCISSOR_OFFSET = 56,
    INFERNO_METAL_RESOURCE_DRAW_VIEWPORT_OFFSET = 72,
    INFERNO_METAL_RESOURCE_DRAW_BLEND_COLOR_OFFSET = 120,
    INFERNO_METAL_RESOURCE_DRAW_RESERVED_OFFSET = 136,
    INFERNO_METAL_RESOURCE_DRAW_RESERVED_SIZE = 24,
};

enum {
    INFERNO_METAL_RESOURCE_BINDING_KIND_OFFSET = 0,
    INFERNO_METAL_RESOURCE_BINDING_INDEX_OFFSET = 4,
    INFERNO_METAL_RESOURCE_BINDING_RESOURCE_OFFSET = 8,
    INFERNO_METAL_RESOURCE_BINDING_LENGTH_OFFSET = 12,
    INFERNO_METAL_RESOURCE_BINDING_OFFSET_OFFSET = 16,
    INFERNO_METAL_RESOURCE_BINDING_RESERVED_OFFSET = 24,
    INFERNO_METAL_RESOURCE_BINDING_RESERVED_SIZE = 8,
};

enum {
    INFERNO_METAL_RESOURCE_QUERY_VERSION_OFFSET = 0,
    INFERNO_METAL_RESOURCE_QUERY_FLAGS_OFFSET = 4,
    INFERNO_METAL_RESOURCE_QUERY_LIBRARY_COUNT_OFFSET = 8,
    INFERNO_METAL_RESOURCE_QUERY_PAYLOAD_SIZE_OFFSET = 12,
    INFERNO_METAL_RESOURCE_QUERY_RESERVED_OFFSET = 16,
    INFERNO_METAL_RESOURCE_QUERY_RESERVED_SIZE = 48,
};

enum {
    INFERNO_METAL_RESOURCE_RESULT_TEXTURE_COUNT_OFFSET = 48,
    INFERNO_METAL_RESOURCE_RESULT_RESERVED0_OFFSET = 52,
    INFERNO_METAL_RESOURCE_RESULT_RESERVED0_SIZE = 12,
};

enum {
    INFERNO_METAL_RESOURCE_LIBRARY_SOURCE = 1,
    INFERNO_METAL_RESOURCE_LIBRARY_METALLIB = 2,
};

enum {
    INFERNO_METAL_RESOURCE_PIXEL_FORMAT_RGBA8_UNORM = 70,
    INFERNO_METAL_RESOURCE_PIXEL_FORMAT_RGBA8_UNORM_SRGB = 71,
    INFERNO_METAL_RESOURCE_PIXEL_FORMAT_RGBA8_SNORM = 72,
    INFERNO_METAL_RESOURCE_PIXEL_FORMAT_BGRA8_UNORM = 80,
    INFERNO_METAL_RESOURCE_PIXEL_FORMAT_BGRA8_UNORM_SRGB = 81,
};

enum {
    INFERNO_METAL_RESOURCE_TEXTURE_USAGE_SHADER_READ = 1U << 0,
    INFERNO_METAL_RESOURCE_TEXTURE_USAGE_SHADER_WRITE = 1U << 1,
    INFERNO_METAL_RESOURCE_TEXTURE_USAGE_RENDER_TARGET = 1U << 2,
    INFERNO_METAL_RESOURCE_TEXTURE_USAGE_MASK =
        INFERNO_METAL_RESOURCE_TEXTURE_USAGE_SHADER_READ |
        INFERNO_METAL_RESOURCE_TEXTURE_USAGE_SHADER_WRITE |
        INFERNO_METAL_RESOURCE_TEXTURE_USAGE_RENDER_TARGET,
    INFERNO_METAL_RESOURCE_TEXTURE_ALLOW_GPU_OPTIMIZED_CONTENTS = 1U << 0,
    INFERNO_METAL_RESOURCE_TEXTURE_FLAG_MASK =
        INFERNO_METAL_RESOURCE_TEXTURE_ALLOW_GPU_OPTIMIZED_CONTENTS,
};

enum {
    INFERNO_METAL_RESOURCE_FILTER_NEAREST = 0,
    INFERNO_METAL_RESOURCE_FILTER_LINEAR = 1,
    INFERNO_METAL_RESOURCE_MIP_FILTER_NOT_MIPMAPPED = 0,
    INFERNO_METAL_RESOURCE_MIP_FILTER_NEAREST = 1,
    INFERNO_METAL_RESOURCE_MIP_FILTER_LINEAR = 2,
    INFERNO_METAL_RESOURCE_ADDRESS_CLAMP_TO_EDGE = 0,
    INFERNO_METAL_RESOURCE_ADDRESS_MIRROR_REPEAT = 1,
    INFERNO_METAL_RESOURCE_ADDRESS_CLAMP_TO_ZERO = 2,
    INFERNO_METAL_RESOURCE_ADDRESS_REPEAT = 3,
    INFERNO_METAL_RESOURCE_ADDRESS_MIRROR_CLAMP_TO_EDGE = 4,
    INFERNO_METAL_RESOURCE_ADDRESS_CLAMP_TO_BORDER_COLOR = 5,
    INFERNO_METAL_RESOURCE_BORDER_TRANSPARENT_BLACK = 0,
    INFERNO_METAL_RESOURCE_BORDER_OPAQUE_BLACK = 1,
    INFERNO_METAL_RESOURCE_BORDER_OPAQUE_WHITE = 2,
    INFERNO_METAL_RESOURCE_REDUCTION_WEIGHTED_AVERAGE = 0,
};

enum {
    INFERNO_METAL_RESOURCE_COMPARE_NEVER = 0,
    INFERNO_METAL_RESOURCE_COMPARE_LESS = 1,
    INFERNO_METAL_RESOURCE_COMPARE_EQUAL = 2,
    INFERNO_METAL_RESOURCE_COMPARE_LESS_EQUAL = 3,
    INFERNO_METAL_RESOURCE_COMPARE_GREATER = 4,
    INFERNO_METAL_RESOURCE_COMPARE_NOT_EQUAL = 5,
    INFERNO_METAL_RESOURCE_COMPARE_GREATER_EQUAL = 6,
    INFERNO_METAL_RESOURCE_COMPARE_ALWAYS = 7,
};

enum {
    INFERNO_METAL_RESOURCE_COMMAND_COMPUTE = 1,
    INFERNO_METAL_RESOURCE_COMMAND_RENDER = 2,
    INFERNO_METAL_RESOURCE_LOAD_DONT_CARE = 0,
    INFERNO_METAL_RESOURCE_LOAD_LOAD = 1,
    INFERNO_METAL_RESOURCE_LOAD_CLEAR = 2,
    INFERNO_METAL_RESOURCE_STORE_STORE = 1,
};

enum {
    INFERNO_METAL_RESOURCE_BLEND_FACTOR_ZERO = 0,
    INFERNO_METAL_RESOURCE_BLEND_FACTOR_ONE = 1,
    INFERNO_METAL_RESOURCE_BLEND_FACTOR_SOURCE_COLOR = 2,
    INFERNO_METAL_RESOURCE_BLEND_FACTOR_ONE_MINUS_SOURCE_COLOR = 3,
    INFERNO_METAL_RESOURCE_BLEND_FACTOR_SOURCE_ALPHA = 4,
    INFERNO_METAL_RESOURCE_BLEND_FACTOR_ONE_MINUS_SOURCE_ALPHA = 5,
    INFERNO_METAL_RESOURCE_BLEND_FACTOR_DESTINATION_COLOR = 6,
    INFERNO_METAL_RESOURCE_BLEND_FACTOR_ONE_MINUS_DESTINATION_COLOR = 7,
    INFERNO_METAL_RESOURCE_BLEND_FACTOR_DESTINATION_ALPHA = 8,
    INFERNO_METAL_RESOURCE_BLEND_FACTOR_ONE_MINUS_DESTINATION_ALPHA = 9,
    INFERNO_METAL_RESOURCE_BLEND_FACTOR_SOURCE_ALPHA_SATURATED = 10,
    INFERNO_METAL_RESOURCE_BLEND_FACTOR_BLEND_COLOR = 11,
    INFERNO_METAL_RESOURCE_BLEND_FACTOR_ONE_MINUS_BLEND_COLOR = 12,
    INFERNO_METAL_RESOURCE_BLEND_FACTOR_BLEND_ALPHA = 13,
    INFERNO_METAL_RESOURCE_BLEND_FACTOR_ONE_MINUS_BLEND_ALPHA = 14,
    INFERNO_METAL_RESOURCE_BLEND_FACTOR_SOURCE1_COLOR = 15,
    INFERNO_METAL_RESOURCE_BLEND_FACTOR_ONE_MINUS_SOURCE1_COLOR = 16,
    INFERNO_METAL_RESOURCE_BLEND_FACTOR_SOURCE1_ALPHA = 17,
    INFERNO_METAL_RESOURCE_BLEND_FACTOR_ONE_MINUS_SOURCE1_ALPHA = 18,
    INFERNO_METAL_RESOURCE_BLEND_OPERATION_ADD = 0,
    INFERNO_METAL_RESOURCE_BLEND_OPERATION_SUBTRACT = 1,
    INFERNO_METAL_RESOURCE_BLEND_OPERATION_REVERSE_SUBTRACT = 2,
    INFERNO_METAL_RESOURCE_BLEND_OPERATION_MIN = 3,
    INFERNO_METAL_RESOURCE_BLEND_OPERATION_MAX = 4,
    INFERNO_METAL_RESOURCE_WRITE_MASK_RED = 1U << 3,
    INFERNO_METAL_RESOURCE_WRITE_MASK_GREEN = 1U << 2,
    INFERNO_METAL_RESOURCE_WRITE_MASK_BLUE = 1U << 1,
    INFERNO_METAL_RESOURCE_WRITE_MASK_ALPHA = 1U << 0,
    INFERNO_METAL_RESOURCE_WRITE_MASK_ALL = 15,
};

enum {
    INFERNO_METAL_RESOURCE_PRIMITIVE_POINT = 0,
    INFERNO_METAL_RESOURCE_PRIMITIVE_LINE = 1,
    INFERNO_METAL_RESOURCE_PRIMITIVE_LINE_STRIP = 2,
    INFERNO_METAL_RESOURCE_PRIMITIVE_TRIANGLE = 3,
    INFERNO_METAL_RESOURCE_PRIMITIVE_TRIANGLE_STRIP = 4,
    INFERNO_METAL_RESOURCE_CULL_NONE = 0,
    INFERNO_METAL_RESOURCE_CULL_FRONT = 1,
    INFERNO_METAL_RESOURCE_CULL_BACK = 2,
    INFERNO_METAL_RESOURCE_WINDING_CLOCKWISE = 0,
    INFERNO_METAL_RESOURCE_WINDING_COUNTER_CLOCKWISE = 1,
    INFERNO_METAL_RESOURCE_FILL_MODE_FILL = 0,
    INFERNO_METAL_RESOURCE_FILL_MODE_LINES = 1,
};

enum {
    INFERNO_METAL_RESOURCE_DRAW_SCISSOR = 1U << 0,
    INFERNO_METAL_RESOURCE_DRAW_VIEWPORT = 1U << 1,
    INFERNO_METAL_RESOURCE_DRAW_BLEND_COLOR = 1U << 2,
    INFERNO_METAL_RESOURCE_DRAW_FLAG_MASK =
        INFERNO_METAL_RESOURCE_DRAW_SCISSOR |
        INFERNO_METAL_RESOURCE_DRAW_VIEWPORT |
        INFERNO_METAL_RESOURCE_DRAW_BLEND_COLOR,
};

enum {
    INFERNO_METAL_RESOURCE_BINDING_BUFFER = 1,
    INFERNO_METAL_RESOURCE_BINDING_INLINE = 2,
    INFERNO_METAL_RESOURCE_BINDING_THREADGROUP = 3,
    INFERNO_METAL_RESOURCE_BINDING_TEXTURE = 4,
    INFERNO_METAL_RESOURCE_BINDING_SAMPLER = 5,
};

enum {
    INFERNO_METAL_RESOURCE_OUTCOME_UNSUPPORTED_STATE = 9,
    INFERNO_METAL_RESOURCE_OUTCOME_RESOURCE_FAILED = 10,
    INFERNO_METAL_RESOURCE_PHASE_RESOURCE = 7,
    INFERNO_METAL_RESOURCE_RECORD_LIBRARY = 6,
    INFERNO_METAL_RESOURCE_RECORD_RENDER_PIPELINE = 7,
    INFERNO_METAL_RESOURCE_RECORD_TEXTURE = 8,
    INFERNO_METAL_RESOURCE_RECORD_SAMPLER = 9,
    INFERNO_METAL_RESOURCE_RECORD_COMMAND = 10,
    INFERNO_METAL_RESOURCE_RECORD_DRAW = 11,
};

enum {
    INFERNO_METAL_RESOURCE_COMPILER_STAGE_OFFSET = 56,
    INFERNO_METAL_RESOURCE_COMPILER_RESERVED_OFFSET = 60,
    INFERNO_METAL_RESOURCE_COMPILER_RESERVED_SIZE = 4,
    INFERNO_METAL_RESOURCE_COMPILER_STAGE_NONE = 0,
    INFERNO_METAL_RESOURCE_COMPILER_STAGE_VERTEX = 1,
    INFERNO_METAL_RESOURCE_COMPILER_STAGE_FRAGMENT = 2,
};

enum {
    INFERNO_METAL_RESOURCE_RENDER_RESULT_ALLOCATED_SIZE_OFFSET = 0,
    INFERNO_METAL_RESOURCE_RENDER_RESULT_IMAGEBLOCK_SAMPLE_LENGTH_OFFSET = 8,
    INFERNO_METAL_RESOURCE_RENDER_RESULT_MAX_TOTAL_THREADS_OFFSET = 16,
    INFERNO_METAL_RESOURCE_RENDER_RESULT_MAX_OBJECT_THREADS_OFFSET = 24,
    INFERNO_METAL_RESOURCE_RENDER_RESULT_MAX_MESH_THREADS_OFFSET = 32,
    INFERNO_METAL_RESOURCE_RENDER_RESULT_OBJECT_EXECUTION_WIDTH_OFFSET = 40,
    INFERNO_METAL_RESOURCE_RENDER_RESULT_MESH_EXECUTION_WIDTH_OFFSET = 48,
    INFERNO_METAL_RESOURCE_RENDER_RESULT_MAX_MESH_THREADGROUPS_OFFSET = 56,
    INFERNO_METAL_RESOURCE_RENDER_RESULT_SHADER_VALIDATION_OFFSET = 64,
    INFERNO_METAL_RESOURCE_RENDER_RESULT_TILE_THREADS_OFFSET = 72,
    INFERNO_METAL_RESOURCE_RENDER_RESULT_OBJECT_THREADS_OFFSET = 96,
    INFERNO_METAL_RESOURCE_RENDER_RESULT_MESH_THREADS_OFFSET = 120,
    INFERNO_METAL_RESOURCE_RENDER_RESULT_FLAGS_OFFSET = 144,
    INFERNO_METAL_RESOURCE_RENDER_RESULT_RESERVED_OFFSET = 148,
    INFERNO_METAL_RESOURCE_RENDER_RESULT_RESERVED_SIZE = 364,
};

enum {
    INFERNO_METAL_RESOURCE_RENDER_RESULT_SUPPORTS_INDIRECT = 1U << 0,
    INFERNO_METAL_RESOURCE_RENDER_RESULT_THREADGROUP_MATCHES_TILE = 1U << 1,
    INFERNO_METAL_RESOURCE_RENDER_RESULT_FLAG_MASK =
        INFERNO_METAL_RESOURCE_RENDER_RESULT_SUPPORTS_INDIRECT |
        INFERNO_METAL_RESOURCE_RENDER_RESULT_THREADGROUP_MATCHES_TILE,
};

#ifdef __cplusplus
#define INFERNO_METAL_WIRE_STATIC_ASSERT static_assert
#else
#define INFERNO_METAL_WIRE_STATIC_ASSERT _Static_assert
#endif

INFERNO_METAL_WIRE_STATIC_ASSERT(INFERNO_METAL_RESOURCE_RESERVED_OFFSET +
                                         INFERNO_METAL_RESOURCE_RESERVED_SIZE ==
                                     INFERNO_METAL_RESOURCE_HEADER_SIZE,
                                 "resource header size");
INFERNO_METAL_WIRE_STATIC_ASSERT(
    INFERNO_METAL_RESOURCE_LIBRARY_RESERVED_OFFSET +
            INFERNO_METAL_RESOURCE_LIBRARY_RESERVED_SIZE ==
        INFERNO_METAL_RESOURCE_LIBRARY_RECORD_SIZE,
    "resource library size");
INFERNO_METAL_WIRE_STATIC_ASSERT(
    INFERNO_METAL_RESOURCE_COMPUTE_PIPELINE_NAME_OFFSET +
            INFERNO_METAL_RESOURCE_FUNCTION_NAME_SIZE ==
        INFERNO_METAL_RESOURCE_COMPUTE_PIPELINE_RECORD_SIZE,
    "resource compute pipeline size");
INFERNO_METAL_WIRE_STATIC_ASSERT(
    INFERNO_METAL_RESOURCE_RENDER_PIPELINE_FRAGMENT_NAME_OFFSET +
            INFERNO_METAL_RESOURCE_FUNCTION_NAME_SIZE ==
        INFERNO_METAL_RESOURCE_RENDER_PIPELINE_RECORD_SIZE,
    "resource render pipeline size");
INFERNO_METAL_WIRE_STATIC_ASSERT(
    INFERNO_METAL_RESOURCE_BUFFER_RESERVED_OFFSET +
            INFERNO_METAL_RESOURCE_BUFFER_RESERVED_SIZE ==
        INFERNO_METAL_RESOURCE_BUFFER_RECORD_SIZE,
    "resource buffer size");
INFERNO_METAL_WIRE_STATIC_ASSERT(
    INFERNO_METAL_RESOURCE_TEXTURE_RESERVED_OFFSET +
            INFERNO_METAL_RESOURCE_TEXTURE_RESERVED_SIZE ==
        INFERNO_METAL_RESOURCE_TEXTURE_RECORD_SIZE,
    "resource texture size");
INFERNO_METAL_WIRE_STATIC_ASSERT(
    INFERNO_METAL_RESOURCE_SAMPLER_RESERVED_OFFSET +
            INFERNO_METAL_RESOURCE_SAMPLER_RESERVED_SIZE ==
        INFERNO_METAL_RESOURCE_SAMPLER_RECORD_SIZE,
    "resource sampler size");
INFERNO_METAL_WIRE_STATIC_ASSERT(
    INFERNO_METAL_RESOURCE_COMMAND_COMPUTE_RESERVED_OFFSET +
            INFERNO_METAL_RESOURCE_COMMAND_COMPUTE_RESERVED_SIZE ==
        INFERNO_METAL_RESOURCE_COMMAND_RECORD_SIZE,
    "resource compute command size");
INFERNO_METAL_WIRE_STATIC_ASSERT(
    INFERNO_METAL_RESOURCE_COMMAND_RENDER_RESERVED_OFFSET +
            INFERNO_METAL_RESOURCE_COMMAND_RENDER_RESERVED_SIZE ==
        INFERNO_METAL_RESOURCE_COMMAND_RECORD_SIZE,
    "resource render command size");
INFERNO_METAL_WIRE_STATIC_ASSERT(
    INFERNO_METAL_RESOURCE_DRAW_RESERVED_OFFSET +
            INFERNO_METAL_RESOURCE_DRAW_RESERVED_SIZE ==
        INFERNO_METAL_RESOURCE_DRAW_RECORD_SIZE,
    "resource draw size");
INFERNO_METAL_WIRE_STATIC_ASSERT(
    INFERNO_METAL_RESOURCE_BINDING_RESERVED_OFFSET +
            INFERNO_METAL_RESOURCE_BINDING_RESERVED_SIZE ==
        INFERNO_METAL_RESOURCE_BINDING_RECORD_SIZE,
    "resource binding size");
INFERNO_METAL_WIRE_STATIC_ASSERT(
    INFERNO_METAL_RESOURCE_QUERY_RESERVED_OFFSET +
            INFERNO_METAL_RESOURCE_QUERY_RESERVED_SIZE ==
        INFERNO_METAL_RESOURCE_QUERY_HEADER_SIZE,
    "resource query header size");
INFERNO_METAL_WIRE_STATIC_ASSERT(
    INFERNO_METAL_RESOURCE_RESULT_RESERVED0_OFFSET +
            INFERNO_METAL_RESOURCE_RESULT_RESERVED0_SIZE ==
        INFERNO_METAL_BATCH_RESULT_ERROR_CODE_OFFSET,
    "resource result header size");
INFERNO_METAL_WIRE_STATIC_ASSERT(
    INFERNO_METAL_RESOURCE_RENDER_RESULT_RESERVED_OFFSET +
            INFERNO_METAL_RESOURCE_RENDER_RESULT_RESERVED_SIZE ==
        INFERNO_METAL_RESOURCE_RENDER_RESULT_SIZE,
    "resource render result size");
INFERNO_METAL_WIRE_STATIC_ASSERT(
    INFERNO_METAL_RESOURCE_COMPILER_RENDER_RESULT_OFFSET +
            INFERNO_METAL_RESOURCE_RENDER_RESULT_SIZE ==
        17168U,
    "resource compiler render result end");

#undef INFERNO_METAL_WIRE_STATIC_ASSERT

enum {
    INFERNO_METAL_OPTIONS_DEFAULT = 0,
};

enum {
    INFERNO_METAL_DESCRIPTOR_OPTIONS_OFFSET = 192,
    INFERNO_METAL_DESCRIPTOR_RESERVED_OFFSET = 196,
    INFERNO_METAL_DESCRIPTOR_RESERVED_SIZE = 60,
};

#define INFERNO_METAL_COMPILER_HEADER_SIZE 64U
#define INFERNO_METAL_COMPILER_DOMAIN_SIZE 128U
#define INFERNO_METAL_COMPILER_DESCRIPTION_SIZE 16384U
#define INFERNO_METAL_COMPILER_FUNCTION_NAME_SIZE 248U
#define INFERNO_METAL_COMPILER_PIPELINE_SIZE 64U
#define INFERNO_METAL_COMPILER_LIBRARY_SIZE 512U
#define INFERNO_METAL_COMPILER_LIBRARY_NAME_SIZE 496U
#define INFERNO_METAL_COMPILER_FUNCTION_RECORD_BASE_SIZE 296U
#define INFERNO_METAL_COMPILER_METADATA_RECORD_SIZE 128U
#define INFERNO_METAL_COMPILER_METADATA_NAME_SIZE 104U
#define INFERNO_METAL_COMPILER_MAX_FUNCTIONS 1024U
#define INFERNO_METAL_COMPILER_MAX_METADATA_RECORDS 8192U
#define INFERNO_METAL_COMPILER_MIN_OUTPUT 17168U
#define INFERNO_METAL_COMPILER_MAX_OUTPUT                   \
    (INFERNO_METAL_COMPILER_MIN_OUTPUT +                    \
     INFERNO_METAL_COMPILER_MAX_FUNCTIONS *                 \
         INFERNO_METAL_COMPILER_FUNCTION_RECORD_BASE_SIZE + \
     INFERNO_METAL_COMPILER_MAX_METADATA_RECORDS *          \
         INFERNO_METAL_COMPILER_METADATA_RECORD_SIZE)

enum {
    INFERNO_METAL_COMPILER_VERSION_OFFSET = 0,
    INFERNO_METAL_COMPILER_OPCODE_OFFSET = 4,
    INFERNO_METAL_COMPILER_SEQUENCE_OFFSET = 8,
    INFERNO_METAL_COMPILER_OUTCOME_OFFSET = 16,
    INFERNO_METAL_COMPILER_PHASE_OFFSET = 20,
    INFERNO_METAL_COMPILER_FLAGS_OFFSET = 24,
    INFERNO_METAL_COMPILER_FUNCTION_COUNT_OFFSET = 28,
    INFERNO_METAL_COMPILER_FUNCTION_TYPE_OFFSET = 32,
    INFERNO_METAL_COMPILER_MAX_TOTAL_THREADS_OFFSET = 36,
    INFERNO_METAL_COMPILER_THREAD_EXECUTION_WIDTH_OFFSET = 40,
    INFERNO_METAL_COMPILER_STATIC_THREADGROUP_MEMORY_OFFSET = 44,
    INFERNO_METAL_COMPILER_REQUIRED_OUTPUT_SIZE_OFFSET = 48,
    INFERNO_METAL_COMPILER_METADATA_RECORD_COUNT_OFFSET = 52,
    INFERNO_METAL_COMPILER_RESERVED_OFFSET = 56,
    INFERNO_METAL_COMPILER_RESERVED_SIZE = 8,
    INFERNO_METAL_COMPILER_ERROR_CODE_OFFSET = 64,
    INFERNO_METAL_COMPILER_DOMAIN_LENGTH_OFFSET = 72,
    INFERNO_METAL_COMPILER_DESCRIPTION_LENGTH_OFFSET = 76,
    INFERNO_METAL_COMPILER_DOMAIN_OFFSET = 80,
    INFERNO_METAL_COMPILER_DESCRIPTION_OFFSET = 208,
    INFERNO_METAL_COMPILER_PIPELINE_OFFSET = 16592,
    INFERNO_METAL_COMPILER_LIBRARY_OFFSET = 16656,
    INFERNO_METAL_COMPILER_FUNCTIONS_OFFSET = 17168,
};

enum {
    INFERNO_METAL_COMPILER_RECORD_TYPE_OFFSET = 0,
    INFERNO_METAL_COMPILER_RECORD_NAME_LENGTH_OFFSET = 4,
    INFERNO_METAL_COMPILER_RECORD_PATCH_TYPE_OFFSET = 8,
    INFERNO_METAL_COMPILER_RECORD_FLAGS_OFFSET = 12,
    INFERNO_METAL_COMPILER_RECORD_PATCH_CONTROL_POINT_COUNT_OFFSET = 16,
    INFERNO_METAL_COMPILER_RECORD_OPTIONS_OFFSET = 24,
    INFERNO_METAL_COMPILER_RECORD_CONSTANT_COUNT_OFFSET = 32,
    INFERNO_METAL_COMPILER_RECORD_VERTEX_ATTRIBUTE_COUNT_OFFSET = 36,
    INFERNO_METAL_COMPILER_RECORD_STAGE_INPUT_ATTRIBUTE_COUNT_OFFSET = 40,
    INFERNO_METAL_COMPILER_RECORD_SIZE_OFFSET = 44,
    INFERNO_METAL_COMPILER_RECORD_NAME_OFFSET = 48,
    INFERNO_METAL_COMPILER_RECORD_METADATA_OFFSET = 296,
};

enum {
    INFERNO_METAL_COMPILER_METADATA_KIND_OFFSET = 0,
    INFERNO_METAL_COMPILER_METADATA_DATA_TYPE_OFFSET = 4,
    INFERNO_METAL_COMPILER_METADATA_INDEX_OFFSET = 8,
    INFERNO_METAL_COMPILER_METADATA_FLAGS_OFFSET = 16,
    INFERNO_METAL_COMPILER_METADATA_NAME_LENGTH_OFFSET = 20,
    INFERNO_METAL_COMPILER_METADATA_NAME_OFFSET = 24,
};

enum {
    INFERNO_METAL_COMPILER_PIPELINE_ALLOCATED_SIZE_OFFSET = 16592,
    INFERNO_METAL_COMPILER_PIPELINE_REQUIRED_WIDTH_OFFSET = 16600,
    INFERNO_METAL_COMPILER_PIPELINE_REQUIRED_HEIGHT_OFFSET = 16608,
    INFERNO_METAL_COMPILER_PIPELINE_REQUIRED_DEPTH_OFFSET = 16616,
    INFERNO_METAL_COMPILER_PIPELINE_SHADER_VALIDATION_OFFSET = 16624,
    INFERNO_METAL_COMPILER_PIPELINE_IMAGEBLOCK_MEMORY_LENGTH_OFFSET = 16632,
    INFERNO_METAL_COMPILER_PIPELINE_FLAGS_OFFSET = 16640,
    INFERNO_METAL_COMPILER_PIPELINE_RESERVED_OFFSET = 16644,
    INFERNO_METAL_COMPILER_PIPELINE_RESERVED_SIZE = 12,
};

enum {
    INFERNO_METAL_COMPILER_LIBRARY_TYPE_OFFSET = 16656,
    INFERNO_METAL_COMPILER_LIBRARY_FLAGS_OFFSET = 16660,
    INFERNO_METAL_COMPILER_LIBRARY_NAME_LENGTH_OFFSET = 16664,
    INFERNO_METAL_COMPILER_LIBRARY_RESERVED_OFFSET = 16668,
    INFERNO_METAL_COMPILER_LIBRARY_NAME_OFFSET = 16672,
};

enum {
    INFERNO_METAL_COMPILER_OUTCOME_OK = 0,
    INFERNO_METAL_COMPILER_OUTCOME_COMPILE_FAILED = 1,
    INFERNO_METAL_COMPILER_OUTCOME_FUNCTION_NOT_FOUND = 2,
    INFERNO_METAL_COMPILER_OUTCOME_FUNCTION_TYPE_MISMATCH = 3,
    INFERNO_METAL_COMPILER_OUTCOME_INVENTORY_UNSUPPORTED = 4,
    INFERNO_METAL_COMPILER_OUTCOME_OUTPUT_TOO_SMALL = 5,
    INFERNO_METAL_COMPILER_OUTCOME_SPECIALIZATION_REQUIRED = 6,
};

enum {
    INFERNO_METAL_COMPILER_FUNCTION_FLAG_HAS_VERTEX_ATTRIBUTES = 1U << 0,
    INFERNO_METAL_COMPILER_FUNCTION_FLAG_HAS_STAGE_INPUT_ATTRIBUTES = 1U << 1,
    INFERNO_METAL_COMPILER_FUNCTION_FLAG_MASK =
        INFERNO_METAL_COMPILER_FUNCTION_FLAG_HAS_VERTEX_ATTRIBUTES |
        INFERNO_METAL_COMPILER_FUNCTION_FLAG_HAS_STAGE_INPUT_ATTRIBUTES,
};

enum {
    INFERNO_METAL_COMPILER_METADATA_CONSTANT = 1,
    INFERNO_METAL_COMPILER_METADATA_VERTEX_ATTRIBUTE = 2,
    INFERNO_METAL_COMPILER_METADATA_STAGE_INPUT_ATTRIBUTE = 3,
};

enum {
    INFERNO_METAL_COMPILER_CONSTANT_FLAG_REQUIRED = 1U << 0,
    INFERNO_METAL_COMPILER_CONSTANT_FLAG_MASK =
        INFERNO_METAL_COMPILER_CONSTANT_FLAG_REQUIRED,
};

enum {
    INFERNO_METAL_COMPILER_ATTRIBUTE_FLAG_ACTIVE = 1U << 0,
    INFERNO_METAL_COMPILER_ATTRIBUTE_FLAG_PATCH_DATA = 1U << 1,
    INFERNO_METAL_COMPILER_ATTRIBUTE_FLAG_PATCH_CONTROL_POINT_DATA = 1U << 2,
    INFERNO_METAL_COMPILER_ATTRIBUTE_FLAG_MASK =
        INFERNO_METAL_COMPILER_ATTRIBUTE_FLAG_ACTIVE |
        INFERNO_METAL_COMPILER_ATTRIBUTE_FLAG_PATCH_DATA |
        INFERNO_METAL_COMPILER_ATTRIBUTE_FLAG_PATCH_CONTROL_POINT_DATA,
};

enum {
    INFERNO_METAL_COMPILER_PIPELINE_FLAG_SUPPORTS_INDIRECT_COMMAND_BUFFERS =
        1U << 0,
    INFERNO_METAL_COMPILER_PIPELINE_FLAG_MASK =
        INFERNO_METAL_COMPILER_PIPELINE_FLAG_SUPPORTS_INDIRECT_COMMAND_BUFFERS,
};

enum {
    INFERNO_METAL_COMPILER_LIBRARY_FLAG_HAS_INSTALL_NAME = 1U << 0,
    INFERNO_METAL_COMPILER_LIBRARY_FLAG_MASK =
        INFERNO_METAL_COMPILER_LIBRARY_FLAG_HAS_INSTALL_NAME,
};

enum {
    INFERNO_METAL_LIBRARY_TYPE_EXECUTABLE = 0,
    INFERNO_METAL_LIBRARY_TYPE_DYNAMIC = 1,
};

enum {
    INFERNO_METAL_COMPILER_PHASE_NONE = 0,
    INFERNO_METAL_COMPILER_PHASE_LIBRARY = 1,
    INFERNO_METAL_COMPILER_PHASE_INVENTORY = 2,
    INFERNO_METAL_COMPILER_PHASE_FUNCTION = 3,
    INFERNO_METAL_COMPILER_PHASE_PIPELINE = 4,
};

enum {
    INFERNO_METAL_COMPILER_FLAG_DESCRIPTION_TRUNCATED = 1U << 0,
    INFERNO_METAL_COMPILER_FLAG_DOMAIN_TRUNCATED = 1U << 1,
    INFERNO_METAL_COMPILER_FLAG_NO_NSERROR = 1U << 2,
    INFERNO_METAL_COMPILER_FLAG_WARNING = 1U << 3,
    INFERNO_METAL_COMPILER_FLAG_MASK =
        INFERNO_METAL_COMPILER_FLAG_DESCRIPTION_TRUNCATED |
        INFERNO_METAL_COMPILER_FLAG_DOMAIN_TRUNCATED |
        INFERNO_METAL_COMPILER_FLAG_NO_NSERROR |
        INFERNO_METAL_COMPILER_FLAG_WARNING,
};

enum {
    INFERNO_METAL_FUNCTION_TYPE_VERTEX = 1,
    INFERNO_METAL_FUNCTION_TYPE_FRAGMENT = 2,
    INFERNO_METAL_FUNCTION_TYPE_KERNEL = 3,
    INFERNO_METAL_FUNCTION_TYPE_VISIBLE = 5,
    INFERNO_METAL_FUNCTION_TYPE_INTERSECTION = 6,
    INFERNO_METAL_FUNCTION_TYPE_MESH = 7,
    INFERNO_METAL_FUNCTION_TYPE_OBJECT = 8,
};

enum {
    INFERNO_METAL_IDLE = 0,
    INFERNO_METAL_BUSY = 1,
    INFERNO_METAL_DONE = 2,
    INFERNO_METAL_FAILED = 3,
};

enum {
    INFERNO_METAL_OK = 0,
    INFERNO_METAL_BAD_DESCRIPTOR = 1,
    INFERNO_METAL_BAD_MEMORY = 2,
    INFERNO_METAL_BACKEND_ERROR = 3,
};

/* Native field representation; serialize explicitly as little endian. */
typedef struct InfernoMetalCommand {
    uint32_t opcode;
    uint64_t sequence;
    uint64_t source_gpa;
    uint32_t source_size;
    uint32_t input_size;
    uint64_t input_gpa;
    uint64_t output_gpa;
    uint32_t output_size;
    uint32_t width;
    uint32_t height;
    /* Compute depth, or render vertex count. */
    uint32_t depth;
    uint32_t options;
    char function[64];
    char fragment[64];
} InfernoMetalCommand;

/* Byte offsets of aligned 32-bit little-endian device registers. */
enum {
    INFERNO_METAL_REG_MAGIC = 0x00,
    INFERNO_METAL_REG_VERSION = 0x04,
    INFERNO_METAL_REG_STATUS = 0x08,
    INFERNO_METAL_REG_ERROR = 0x0c,
    INFERNO_METAL_REG_DESCRIPTOR_LO = 0x10,
    INFERNO_METAL_REG_DESCRIPTOR_HI = 0x14,
    INFERNO_METAL_REG_SUBMIT = 0x18,
    INFERNO_METAL_REG_SEQUENCE_LO = 0x20,
    INFERNO_METAL_REG_SEQUENCE_HI = 0x24,
    INFERNO_METAL_REG_PENDING = 0x28,
    INFERNO_METAL_REG_IRQ_ENABLE = 0x2c,
    INFERNO_METAL_REG_ACK = 0x30,
    INFERNO_METAL_REG_RESET = 0x34,
    INFERNO_METAL_REG_PROGRESS = 0x38,
    INFERNO_METAL_REGISTER_SIZE = 0x3c,
};

enum {
    INFERNO_METAL_PROGRESS_SCHEDULED = 1U << 0,
    INFERNO_METAL_PROGRESS_MASK = INFERNO_METAL_PROGRESS_SCHEDULED,
};

#endif
