/*
 * Inferno guest-to-host Metal execution bridge.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef STANDARD_HEADERS_INFERNO_METAL_H
#define STANDARD_HEADERS_INFERNO_METAL_H

#include <stdint.h>

#define INFERNO_METAL_MAGIC 0x4c544d49U
#define INFERNO_METAL_VERSION 4U
#define INFERNO_METAL_DESCRIPTOR_SIZE 256U
#define INFERNO_METAL_MAX_SOURCE (64U * 1024U)
#define INFERNO_METAL_MAX_BUFFER (16U * 1024U * 1024U)
#define INFERNO_METAL_MAX_THREADS (16U * 1024U * 1024U)

enum {
    INFERNO_METAL_COMPUTE = 1,
    INFERNO_METAL_RENDER = 2,
    INFERNO_METAL_CLEAR = 3,
    INFERNO_METAL_QUERY_LIBRARY = 4,
    INFERNO_METAL_QUERY_PIPELINE = 5,
    INFERNO_METAL_QUERY_IMAGEBLOCK = 6,
    INFERNO_METAL_BATCH = 7,
};

#define INFERNO_METAL_BATCH_HEADER_SIZE 64U
#define INFERNO_METAL_BATCH_PIPELINE_RECORD_SIZE 80U
#define INFERNO_METAL_BATCH_BUFFER_RECORD_SIZE 16U
#define INFERNO_METAL_BATCH_DISPATCH_RECORD_SIZE 64U
#define INFERNO_METAL_BATCH_BINDING_RECORD_SIZE 32U
#define INFERNO_METAL_BATCH_RESULT_SIZE 16640U
#define INFERNO_METAL_BATCH_MAX_PIPELINES 8U
#define INFERNO_METAL_BATCH_MAX_BUFFERS 64U
#define INFERNO_METAL_BATCH_MAX_DISPATCHES 64U
#define INFERNO_METAL_BATCH_MAX_BINDINGS 1024U
#define INFERNO_METAL_BATCH_MAX_INLINE (64U * 1024U)
#define INFERNO_METAL_BATCH_MAX_SOURCE \
    (INFERNO_METAL_BATCH_MAX_PIPELINES * INFERNO_METAL_MAX_SOURCE)
#define INFERNO_METAL_BATCH_MAX_BUFFER_LENGTH \
    (INFERNO_METAL_MAX_BUFFER - INFERNO_METAL_BATCH_MAX_INLINE)
#define INFERNO_METAL_BATCH_MAX_IMAGES \
    (INFERNO_METAL_MAX_BUFFER - INFERNO_METAL_BATCH_RESULT_SIZE)

enum {
    INFERNO_METAL_BATCH_VERSION_OFFSET = 0,
    INFERNO_METAL_BATCH_FLAGS_OFFSET = 4,
    INFERNO_METAL_BATCH_PIPELINE_COUNT_OFFSET = 8,
    INFERNO_METAL_BATCH_BUFFER_COUNT_OFFSET = 12,
    INFERNO_METAL_BATCH_DISPATCH_COUNT_OFFSET = 16,
    INFERNO_METAL_BATCH_BINDING_COUNT_OFFSET = 20,
    INFERNO_METAL_BATCH_INLINE_SIZE_OFFSET = 24,
    INFERNO_METAL_BATCH_SOURCE_SIZE_OFFSET = 28,
    INFERNO_METAL_BATCH_IMAGES_SIZE_OFFSET = 32,
    INFERNO_METAL_BATCH_RESERVED_OFFSET = 36,
    INFERNO_METAL_BATCH_RESERVED_SIZE = 28,
};

enum {
    INFERNO_METAL_BATCH_PIPELINE_SOURCE_OFFSET = 0,
    INFERNO_METAL_BATCH_PIPELINE_SOURCE_SIZE_OFFSET = 4,
    INFERNO_METAL_BATCH_PIPELINE_FLAGS_OFFSET = 8,
    INFERNO_METAL_BATCH_PIPELINE_RESERVED_OFFSET = 12,
    INFERNO_METAL_BATCH_PIPELINE_NAME_OFFSET = 16,
};

enum {
    INFERNO_METAL_BATCH_BUFFER_LENGTH_OFFSET = 0,
    INFERNO_METAL_BATCH_BUFFER_FLAGS_OFFSET = 4,
    INFERNO_METAL_BATCH_BUFFER_RESERVED_OFFSET = 8,
};

enum {
    INFERNO_METAL_BATCH_DISPATCH_PIPELINE_OFFSET = 0,
    INFERNO_METAL_BATCH_DISPATCH_MODE_OFFSET = 4,
    INFERNO_METAL_BATCH_DISPATCH_BINDING_START_OFFSET = 8,
    INFERNO_METAL_BATCH_DISPATCH_BINDING_COUNT_OFFSET = 12,
    INFERNO_METAL_BATCH_DISPATCH_GRID_WIDTH_OFFSET = 16,
    INFERNO_METAL_BATCH_DISPATCH_GRID_HEIGHT_OFFSET = 20,
    INFERNO_METAL_BATCH_DISPATCH_GRID_DEPTH_OFFSET = 24,
    INFERNO_METAL_BATCH_DISPATCH_GROUP_WIDTH_OFFSET = 28,
    INFERNO_METAL_BATCH_DISPATCH_GROUP_HEIGHT_OFFSET = 32,
    INFERNO_METAL_BATCH_DISPATCH_GROUP_DEPTH_OFFSET = 36,
    INFERNO_METAL_BATCH_DISPATCH_FLAGS_OFFSET = 40,
    INFERNO_METAL_BATCH_DISPATCH_RESERVED_OFFSET = 44,
    INFERNO_METAL_BATCH_DISPATCH_RESERVED_SIZE = 20,
};

enum {
    INFERNO_METAL_BATCH_BINDING_KIND_OFFSET = 0,
    INFERNO_METAL_BATCH_BINDING_INDEX_OFFSET = 4,
    INFERNO_METAL_BATCH_BINDING_RESOURCE_OFFSET = 8,
    INFERNO_METAL_BATCH_BINDING_LENGTH_OFFSET = 12,
    INFERNO_METAL_BATCH_BINDING_OFFSET_OFFSET = 16,
    INFERNO_METAL_BATCH_BINDING_RESERVED_OFFSET = 24,
};

enum {
    INFERNO_METAL_BATCH_DISPATCH_THREADS = 1,
    INFERNO_METAL_BATCH_DISPATCH_THREADGROUPS = 2,
};

enum {
    INFERNO_METAL_BATCH_BINDING_BUFFER = 1,
    INFERNO_METAL_BATCH_BINDING_INLINE = 2,
    INFERNO_METAL_BATCH_BINDING_THREADGROUP = 3,
};

enum {
    INFERNO_METAL_BATCH_RESULT_VERSION_OFFSET = 0,
    INFERNO_METAL_BATCH_RESULT_OPCODE_OFFSET = 4,
    INFERNO_METAL_BATCH_RESULT_SEQUENCE_OFFSET = 8,
    INFERNO_METAL_BATCH_RESULT_OUTCOME_OFFSET = 16,
    INFERNO_METAL_BATCH_RESULT_PHASE_OFFSET = 20,
    INFERNO_METAL_BATCH_RESULT_FLAGS_OFFSET = 24,
    INFERNO_METAL_BATCH_RESULT_FAILED_KIND_OFFSET = 28,
    INFERNO_METAL_BATCH_RESULT_FAILED_INDEX_OFFSET = 32,
    INFERNO_METAL_BATCH_RESULT_BUFFER_COUNT_OFFSET = 36,
    INFERNO_METAL_BATCH_RESULT_IMAGES_SIZE_OFFSET = 40,
    INFERNO_METAL_BATCH_RESULT_HOST_STATUS_OFFSET = 44,
    INFERNO_METAL_BATCH_RESULT_RESERVED0_OFFSET = 48,
    INFERNO_METAL_BATCH_RESULT_RESERVED0_SIZE = 16,
    INFERNO_METAL_BATCH_RESULT_ERROR_CODE_OFFSET = 64,
    INFERNO_METAL_BATCH_RESULT_DOMAIN_LENGTH_OFFSET = 72,
    INFERNO_METAL_BATCH_RESULT_DESCRIPTION_LENGTH_OFFSET = 76,
    INFERNO_METAL_BATCH_RESULT_DOMAIN_OFFSET = 80,
    INFERNO_METAL_BATCH_RESULT_DESCRIPTION_OFFSET = 208,
    INFERNO_METAL_BATCH_RESULT_RESERVED1_OFFSET = 16592,
    INFERNO_METAL_BATCH_RESULT_RESERVED1_SIZE = 48,
    INFERNO_METAL_BATCH_RESULT_IMAGES_OFFSET = 16640,
};

enum {
    INFERNO_METAL_BATCH_OUTCOME_OK = 0,
    INFERNO_METAL_BATCH_OUTCOME_MALFORMED = 1,
    INFERNO_METAL_BATCH_OUTCOME_COMPILE_FAILED = 2,
    INFERNO_METAL_BATCH_OUTCOME_FUNCTION_NOT_FOUND = 3,
    INFERNO_METAL_BATCH_OUTCOME_FUNCTION_TYPE_MISMATCH = 4,
    INFERNO_METAL_BATCH_OUTCOME_SPECIALIZATION_REQUIRED = 5,
    INFERNO_METAL_BATCH_OUTCOME_INVALID_DISPATCH = 6,
    INFERNO_METAL_BATCH_OUTCOME_EXECUTION_FAILED = 7,
    INFERNO_METAL_BATCH_OUTCOME_UNSUPPORTED_HOST = 8,
};

enum {
    INFERNO_METAL_BATCH_PHASE_NONE = 0,
    INFERNO_METAL_BATCH_PHASE_PARSE = 1,
    INFERNO_METAL_BATCH_PHASE_LIBRARY = 2,
    INFERNO_METAL_BATCH_PHASE_FUNCTION = 3,
    INFERNO_METAL_BATCH_PHASE_PIPELINE = 4,
    INFERNO_METAL_BATCH_PHASE_VALIDATE = 5,
    INFERNO_METAL_BATCH_PHASE_EXECUTE = 6,
};

enum {
    INFERNO_METAL_BATCH_RECORD_UNKNOWN = 0,
    INFERNO_METAL_BATCH_RECORD_HEADER = 1,
    INFERNO_METAL_BATCH_RECORD_PIPELINE = 2,
    INFERNO_METAL_BATCH_RECORD_BUFFER = 3,
    INFERNO_METAL_BATCH_RECORD_DISPATCH = 4,
    INFERNO_METAL_BATCH_RECORD_BINDING = 5,
};

enum {
    INFERNO_METAL_BATCH_FLAG_DESCRIPTION_TRUNCATED = 1U << 0,
    INFERNO_METAL_BATCH_FLAG_DOMAIN_TRUNCATED = 1U << 1,
    INFERNO_METAL_BATCH_FLAG_NO_NSERROR = 1U << 2,
    INFERNO_METAL_BATCH_FLAG_WARNING = 1U << 3,
    INFERNO_METAL_BATCH_FLAG_SCHEDULED = 1U << 4,
    INFERNO_METAL_BATCH_FLAG_MASK =
        INFERNO_METAL_BATCH_FLAG_DESCRIPTION_TRUNCATED |
        INFERNO_METAL_BATCH_FLAG_DOMAIN_TRUNCATED |
        INFERNO_METAL_BATCH_FLAG_NO_NSERROR | INFERNO_METAL_BATCH_FLAG_WARNING |
        INFERNO_METAL_BATCH_FLAG_SCHEDULED,
};

enum {
    INFERNO_METAL_HOST_COMMAND_BUFFER_COMPLETED = 4,
    INFERNO_METAL_HOST_COMMAND_BUFFER_ERROR = 5,
};

#define INFERNO_METAL_BATCH_FAILED_INDEX_UNKNOWN UINT32_MAX

enum {
    INFERNO_METAL_OPTIONS_DEFAULT = 0,
};

enum {
    INFERNO_METAL_DESCRIPTOR_OPTIONS_OFFSET = 192,
    INFERNO_METAL_DESCRIPTOR_RESERVED_OFFSET = 196,
    INFERNO_METAL_DESCRIPTOR_RESERVED_SIZE = 60,
};

#define INFERNO_METAL_COMPILER_HEADER_SIZE 64U
#define INFERNO_METAL_COMPILER_DOMAIN_SIZE 128U
#define INFERNO_METAL_COMPILER_DESCRIPTION_SIZE 16384U
#define INFERNO_METAL_COMPILER_FUNCTION_NAME_SIZE 248U
#define INFERNO_METAL_COMPILER_PIPELINE_SIZE 64U
#define INFERNO_METAL_COMPILER_LIBRARY_SIZE 512U
#define INFERNO_METAL_COMPILER_LIBRARY_NAME_SIZE 496U
#define INFERNO_METAL_COMPILER_FUNCTION_RECORD_BASE_SIZE 296U
#define INFERNO_METAL_COMPILER_METADATA_RECORD_SIZE 128U
#define INFERNO_METAL_COMPILER_METADATA_NAME_SIZE 104U
#define INFERNO_METAL_COMPILER_MAX_FUNCTIONS 1024U
#define INFERNO_METAL_COMPILER_MAX_METADATA_RECORDS 8192U
#define INFERNO_METAL_COMPILER_MIN_OUTPUT 17168U
#define INFERNO_METAL_COMPILER_MAX_OUTPUT                   \
    (INFERNO_METAL_COMPILER_MIN_OUTPUT +                    \
     INFERNO_METAL_COMPILER_MAX_FUNCTIONS *                 \
         INFERNO_METAL_COMPILER_FUNCTION_RECORD_BASE_SIZE + \
     INFERNO_METAL_COMPILER_MAX_METADATA_RECORDS *          \
         INFERNO_METAL_COMPILER_METADATA_RECORD_SIZE)

enum {
    INFERNO_METAL_COMPILER_VERSION_OFFSET = 0,
    INFERNO_METAL_COMPILER_OPCODE_OFFSET = 4,
    INFERNO_METAL_COMPILER_SEQUENCE_OFFSET = 8,
    INFERNO_METAL_COMPILER_OUTCOME_OFFSET = 16,
    INFERNO_METAL_COMPILER_PHASE_OFFSET = 20,
    INFERNO_METAL_COMPILER_FLAGS_OFFSET = 24,
    INFERNO_METAL_COMPILER_FUNCTION_COUNT_OFFSET = 28,
    INFERNO_METAL_COMPILER_FUNCTION_TYPE_OFFSET = 32,
    INFERNO_METAL_COMPILER_MAX_TOTAL_THREADS_OFFSET = 36,
    INFERNO_METAL_COMPILER_THREAD_EXECUTION_WIDTH_OFFSET = 40,
    INFERNO_METAL_COMPILER_STATIC_THREADGROUP_MEMORY_OFFSET = 44,
    INFERNO_METAL_COMPILER_REQUIRED_OUTPUT_SIZE_OFFSET = 48,
    INFERNO_METAL_COMPILER_METADATA_RECORD_COUNT_OFFSET = 52,
    INFERNO_METAL_COMPILER_RESERVED_OFFSET = 56,
    INFERNO_METAL_COMPILER_RESERVED_SIZE = 8,
    INFERNO_METAL_COMPILER_ERROR_CODE_OFFSET = 64,
    INFERNO_METAL_COMPILER_DOMAIN_LENGTH_OFFSET = 72,
    INFERNO_METAL_COMPILER_DESCRIPTION_LENGTH_OFFSET = 76,
    INFERNO_METAL_COMPILER_DOMAIN_OFFSET = 80,
    INFERNO_METAL_COMPILER_DESCRIPTION_OFFSET = 208,
    INFERNO_METAL_COMPILER_PIPELINE_OFFSET = 16592,
    INFERNO_METAL_COMPILER_LIBRARY_OFFSET = 16656,
    INFERNO_METAL_COMPILER_FUNCTIONS_OFFSET = 17168,
};

enum {
    INFERNO_METAL_COMPILER_RECORD_TYPE_OFFSET = 0,
    INFERNO_METAL_COMPILER_RECORD_NAME_LENGTH_OFFSET = 4,
    INFERNO_METAL_COMPILER_RECORD_PATCH_TYPE_OFFSET = 8,
    INFERNO_METAL_COMPILER_RECORD_FLAGS_OFFSET = 12,
    INFERNO_METAL_COMPILER_RECORD_PATCH_CONTROL_POINT_COUNT_OFFSET = 16,
    INFERNO_METAL_COMPILER_RECORD_OPTIONS_OFFSET = 24,
    INFERNO_METAL_COMPILER_RECORD_CONSTANT_COUNT_OFFSET = 32,
    INFERNO_METAL_COMPILER_RECORD_VERTEX_ATTRIBUTE_COUNT_OFFSET = 36,
    INFERNO_METAL_COMPILER_RECORD_STAGE_INPUT_ATTRIBUTE_COUNT_OFFSET = 40,
    INFERNO_METAL_COMPILER_RECORD_SIZE_OFFSET = 44,
    INFERNO_METAL_COMPILER_RECORD_NAME_OFFSET = 48,
    INFERNO_METAL_COMPILER_RECORD_METADATA_OFFSET = 296,
};

enum {
    INFERNO_METAL_COMPILER_METADATA_KIND_OFFSET = 0,
    INFERNO_METAL_COMPILER_METADATA_DATA_TYPE_OFFSET = 4,
    INFERNO_METAL_COMPILER_METADATA_INDEX_OFFSET = 8,
    INFERNO_METAL_COMPILER_METADATA_FLAGS_OFFSET = 16,
    INFERNO_METAL_COMPILER_METADATA_NAME_LENGTH_OFFSET = 20,
    INFERNO_METAL_COMPILER_METADATA_NAME_OFFSET = 24,
};

enum {
    INFERNO_METAL_COMPILER_PIPELINE_ALLOCATED_SIZE_OFFSET = 16592,
    INFERNO_METAL_COMPILER_PIPELINE_REQUIRED_WIDTH_OFFSET = 16600,
    INFERNO_METAL_COMPILER_PIPELINE_REQUIRED_HEIGHT_OFFSET = 16608,
    INFERNO_METAL_COMPILER_PIPELINE_REQUIRED_DEPTH_OFFSET = 16616,
    INFERNO_METAL_COMPILER_PIPELINE_SHADER_VALIDATION_OFFSET = 16624,
    INFERNO_METAL_COMPILER_PIPELINE_IMAGEBLOCK_MEMORY_LENGTH_OFFSET = 16632,
    INFERNO_METAL_COMPILER_PIPELINE_FLAGS_OFFSET = 16640,
    INFERNO_METAL_COMPILER_PIPELINE_RESERVED_OFFSET = 16644,
    INFERNO_METAL_COMPILER_PIPELINE_RESERVED_SIZE = 12,
};

enum {
    INFERNO_METAL_COMPILER_LIBRARY_TYPE_OFFSET = 16656,
    INFERNO_METAL_COMPILER_LIBRARY_FLAGS_OFFSET = 16660,
    INFERNO_METAL_COMPILER_LIBRARY_NAME_LENGTH_OFFSET = 16664,
    INFERNO_METAL_COMPILER_LIBRARY_RESERVED_OFFSET = 16668,
    INFERNO_METAL_COMPILER_LIBRARY_NAME_OFFSET = 16672,
};

enum {
    INFERNO_METAL_COMPILER_OUTCOME_OK = 0,
    INFERNO_METAL_COMPILER_OUTCOME_COMPILE_FAILED = 1,
    INFERNO_METAL_COMPILER_OUTCOME_FUNCTION_NOT_FOUND = 2,
    INFERNO_METAL_COMPILER_OUTCOME_FUNCTION_TYPE_MISMATCH = 3,
    INFERNO_METAL_COMPILER_OUTCOME_INVENTORY_UNSUPPORTED = 4,
    INFERNO_METAL_COMPILER_OUTCOME_OUTPUT_TOO_SMALL = 5,
    INFERNO_METAL_COMPILER_OUTCOME_SPECIALIZATION_REQUIRED = 6,
};

enum {
    INFERNO_METAL_COMPILER_FUNCTION_FLAG_HAS_VERTEX_ATTRIBUTES = 1U << 0,
    INFERNO_METAL_COMPILER_FUNCTION_FLAG_HAS_STAGE_INPUT_ATTRIBUTES = 1U << 1,
    INFERNO_METAL_COMPILER_FUNCTION_FLAG_MASK =
        INFERNO_METAL_COMPILER_FUNCTION_FLAG_HAS_VERTEX_ATTRIBUTES |
        INFERNO_METAL_COMPILER_FUNCTION_FLAG_HAS_STAGE_INPUT_ATTRIBUTES,
};

enum {
    INFERNO_METAL_COMPILER_METADATA_CONSTANT = 1,
    INFERNO_METAL_COMPILER_METADATA_VERTEX_ATTRIBUTE = 2,
    INFERNO_METAL_COMPILER_METADATA_STAGE_INPUT_ATTRIBUTE = 3,
};

enum {
    INFERNO_METAL_COMPILER_CONSTANT_FLAG_REQUIRED = 1U << 0,
    INFERNO_METAL_COMPILER_CONSTANT_FLAG_MASK =
        INFERNO_METAL_COMPILER_CONSTANT_FLAG_REQUIRED,
};

enum {
    INFERNO_METAL_COMPILER_ATTRIBUTE_FLAG_ACTIVE = 1U << 0,
    INFERNO_METAL_COMPILER_ATTRIBUTE_FLAG_PATCH_DATA = 1U << 1,
    INFERNO_METAL_COMPILER_ATTRIBUTE_FLAG_PATCH_CONTROL_POINT_DATA = 1U << 2,
    INFERNO_METAL_COMPILER_ATTRIBUTE_FLAG_MASK =
        INFERNO_METAL_COMPILER_ATTRIBUTE_FLAG_ACTIVE |
        INFERNO_METAL_COMPILER_ATTRIBUTE_FLAG_PATCH_DATA |
        INFERNO_METAL_COMPILER_ATTRIBUTE_FLAG_PATCH_CONTROL_POINT_DATA,
};

enum {
    INFERNO_METAL_COMPILER_PIPELINE_FLAG_SUPPORTS_INDIRECT_COMMAND_BUFFERS =
        1U << 0,
    INFERNO_METAL_COMPILER_PIPELINE_FLAG_MASK =
        INFERNO_METAL_COMPILER_PIPELINE_FLAG_SUPPORTS_INDIRECT_COMMAND_BUFFERS,
};

enum {
    INFERNO_METAL_COMPILER_LIBRARY_FLAG_HAS_INSTALL_NAME = 1U << 0,
    INFERNO_METAL_COMPILER_LIBRARY_FLAG_MASK =
        INFERNO_METAL_COMPILER_LIBRARY_FLAG_HAS_INSTALL_NAME,
};

enum {
    INFERNO_METAL_LIBRARY_TYPE_EXECUTABLE = 0,
    INFERNO_METAL_LIBRARY_TYPE_DYNAMIC = 1,
};

enum {
    INFERNO_METAL_COMPILER_PHASE_NONE = 0,
    INFERNO_METAL_COMPILER_PHASE_LIBRARY = 1,
    INFERNO_METAL_COMPILER_PHASE_INVENTORY = 2,
    INFERNO_METAL_COMPILER_PHASE_FUNCTION = 3,
    INFERNO_METAL_COMPILER_PHASE_PIPELINE = 4,
};

enum {
    INFERNO_METAL_COMPILER_FLAG_DESCRIPTION_TRUNCATED = 1U << 0,
    INFERNO_METAL_COMPILER_FLAG_DOMAIN_TRUNCATED = 1U << 1,
    INFERNO_METAL_COMPILER_FLAG_NO_NSERROR = 1U << 2,
    INFERNO_METAL_COMPILER_FLAG_WARNING = 1U << 3,
    INFERNO_METAL_COMPILER_FLAG_MASK =
        INFERNO_METAL_COMPILER_FLAG_DESCRIPTION_TRUNCATED |
        INFERNO_METAL_COMPILER_FLAG_DOMAIN_TRUNCATED |
        INFERNO_METAL_COMPILER_FLAG_NO_NSERROR |
        INFERNO_METAL_COMPILER_FLAG_WARNING,
};

enum {
    INFERNO_METAL_FUNCTION_TYPE_VERTEX = 1,
    INFERNO_METAL_FUNCTION_TYPE_FRAGMENT = 2,
    INFERNO_METAL_FUNCTION_TYPE_KERNEL = 3,
    INFERNO_METAL_FUNCTION_TYPE_VISIBLE = 5,
    INFERNO_METAL_FUNCTION_TYPE_INTERSECTION = 6,
    INFERNO_METAL_FUNCTION_TYPE_MESH = 7,
    INFERNO_METAL_FUNCTION_TYPE_OBJECT = 8,
};

enum {
    INFERNO_METAL_IDLE = 0,
    INFERNO_METAL_BUSY = 1,
    INFERNO_METAL_DONE = 2,
    INFERNO_METAL_FAILED = 3,
};

enum {
    INFERNO_METAL_OK = 0,
    INFERNO_METAL_BAD_DESCRIPTOR = 1,
    INFERNO_METAL_BAD_MEMORY = 2,
    INFERNO_METAL_BACKEND_ERROR = 3,
};

/* Native field representation; serialize explicitly as little endian. */
typedef struct InfernoMetalCommand {
    uint32_t opcode;
    uint64_t sequence;
    uint64_t source_gpa;
    uint32_t source_size;
    uint32_t input_size;
    uint64_t input_gpa;
    uint64_t output_gpa;
    uint32_t output_size;
    uint32_t width;
    uint32_t height;
    /* Compute depth, or render vertex count. */
    uint32_t depth;
    uint32_t options;
    char function[64];
    char fragment[64];
} InfernoMetalCommand;

/* Byte offsets of aligned 32-bit little-endian device registers. */
enum {
    INFERNO_METAL_REG_MAGIC = 0x00,
    INFERNO_METAL_REG_VERSION = 0x04,
    INFERNO_METAL_REG_STATUS = 0x08,
    INFERNO_METAL_REG_ERROR = 0x0c,
    INFERNO_METAL_REG_DESCRIPTOR_LO = 0x10,
    INFERNO_METAL_REG_DESCRIPTOR_HI = 0x14,
    INFERNO_METAL_REG_SUBMIT = 0x18,
    INFERNO_METAL_REG_SEQUENCE_LO = 0x20,
    INFERNO_METAL_REG_SEQUENCE_HI = 0x24,
    INFERNO_METAL_REG_PENDING = 0x28,
    INFERNO_METAL_REG_IRQ_ENABLE = 0x2c,
    INFERNO_METAL_REG_ACK = 0x30,
    INFERNO_METAL_REG_RESET = 0x34,
    INFERNO_METAL_REG_PROGRESS = 0x38,
    INFERNO_METAL_REGISTER_SIZE = 0x3c,
};

enum {
    INFERNO_METAL_PROGRESS_SCHEDULED = 1U << 0,
    INFERNO_METAL_PROGRESS_MASK = INFERNO_METAL_PROGRESS_SCHEDULED,
};

#endif
